### ISSUE TITLE
Couple of queries

### ISSUE THREAD

**Issue by justin-caldicott** [brantburnett/Snappier#106]
Many thanks for putting this together. Snappy.NET still hasn't been updated since, and IronSnappy doesn't seem to be around anymore. This looks just the job if performance is near-native.

I'm wondering:
- Is byte ordering consistent across platform architectures?
- Will there be another release soon? Looks like you've made quite a few changes since the last release in March.

**Comment by brantburnett** [comment]
> * Is byte ordering consistent across platform architectures?

The implementation is written to be byte-order agnostic, it should work on both little-endian and big-endian architectures. However, it has only been tested by me on little-endian architectures (x64 and most ARM64). Additionally, the Snappy compression protocol was specifically designed with performance on little-endian architectures in mind, so expect it to be slower on big-endian.

> * Will there be another release soon? Looks like you've made quite a few changes since the last release in March.

I intend to put out another release soon, probably in the next few weeks. I'm working to get a few more things in before I do, plus I want to give it a very thorough test. But if there's something specific you need I can probably do a beta release sooner.

**Comment by justin-caldicott** [comment]
Many thanks @brantburnett. Now that I dig into it a little, I hadn't realised that most modern platforms are all little-endian anyway. Thanks for the clarification anyway.

No rush on releasing, the last release dropped in where Snappy.NET was and passed all of our integration tests. 💪
