### ISSUE TITLE
Snappy decompression will fail on certain sequence of bytes.

### ISSUE THREAD

**Issue by ak88** [brantburnett/Snappier#88]
Using a certain sequence of bytes decompression will fail with `System.IO.InvalidDataException: 'Invalid copy offset'`

I have made a PR demonstrating this here:
#87

**Comment by brantburnett** [comment]
Thanks for the repro, I believe I have the fix figured out. For general reference, the problem was specific to stream decompression with very long literal segments. Block decompression should have been unaffected.

**Comment by ak88** [comment]
> Thanks for the repro, I believe I have the fix figured out. For general reference, the problem was specific to stream decompression with very long literal segments. Block decompression should have been unaffected.

Awesome! Thanks for the quick reaction.
