### ISSUE TITLE
Add licence type to Nuget Package

### ISSUE THREAD

**Issue by thompson-tomo** [brantburnett/Snappier#92]
### Is your feature request related to a problem? Please describe.
In dependency track this package is reporting as not having a licence type specified

### Describe the solution you'd like
The PackageLicenseExpression property is set in the csproj so that the NUGET package has the information. This can then be included in the SBOM so that analysis can occur in the appropriate tools

### Describe alternatives you've considered
Ignore them, bundle licence file into package & reference the file.

### Additional context
N:a

**Comment by brantburnett** [comment]
Thanks for pointing this out. I've switched to using an SPDX instead of embedding the text in the NuGet, this is releasing shortly as 1.1.5.
